FROM python:3.7.2-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.in /usr/src/app/requirements.in
RUN pip install --upgrade pip \
        && pip install pip-tools \
        && pip-compile /usr/src/app/requirements.in \
        && pip-sync /usr/src/app/requirements.txt

# add entrypoint-prod.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint-prod.sh"]
